### ISSUE TITLE
Include static files, remove dependencies

### ISSUE THREAD

**Issue by dvelasquez** [julon/vue-cli-template-library#6]
How can i add my static files (images, icons etc) in the bundled dist folder?

Also, how can i skip some dependencies which are peerDependencies?

**Comment by julon** [comment]
Hi @dvelasquez! Sorry for the delay, if you want to bundle assets in your js file, you can use https://github.com/rollup/rollup-plugin-image, but if you just want to copy raw assets from one point to another, you can add a gulp or grunt task to copy into the dist since rollup is just used to bundle modules together. 

For the peerDependencies matter, I just updated the rollup.config.js to add all dependencies as externals so it would be skipped in the build process. So you just need to add any libraries you want to skip in dependencies section of the package.json. Hope that helps! Tell me if it works out. :)
